spring:
  application:
    name: quoteNation
  kafka:
    template:
      default-topic: quotes
    bootstrap-servers: localhost:9092
    consumer:
      group-id: quoteNation
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 65536
      buffer-memory: 67108864
      compression-type: lz4
      properties:
        linger.ms: 20
        max.in.flight.requests.per.connection: 1
        enable.idempotence: true

